# Generated by Django 5.2.6 on 2025-10-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_student",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_teacher",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="student_class",
        ),
        migrations.AddField(
            model_name="customuser",
            name="class_name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("teacher", "Teacher"), ("student", "Student")],
                default="student",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="academic_year",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="roll_no",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="subjects",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
