# Generated by Django 5.2.6 on 2025-10-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_lecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="note",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
